### REGISTER

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "aaaaa",
  "email": "aaaaa@test.com",
  "password": "123456789"
}


### LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "aaaaa@test.com",
  "password": "123456789"
}



### Post login
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "aaaaa@test.com",
  "password": "123456789"
}


### GET CURRENT USER (AUTH TEST)

GET http://localhost:3000/api/auth/me
Authorization: Bearer {{login.response.body.token}}
