### REGISTER

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "test",
  "email": "test@example.com",
  "password": "password123"
}


### LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}



### Post login
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}


### GET CURRENT USER (AUTH TEST)

GET http://localhost:3000/api/auth/me
Authorization: Bearer {{login.response.body.token}}
