###  INVALID REGISTER (should fail validation)
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "Khaled1",
  "email": "khaled1@gmail.com",
  "password": "123456789"
}


###  VALID REGISTER
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "Khaled1",
  "email": "khaled1@gmail.com",
  "password": "123456789"
}


###  LOGIN WRONG PASSWORD
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "adminK@gmail.com",
  "password": "123456789"
}


### LOGIN
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "adminK@gmail.com",
  "password": "123456789"
}


###  GET CURRENT USER (TOKEN TEST)
GET http://localhost:3000/api/auth/me
Authorization: Bearer {{login.response.body.token}}


### NO TOKEN (should return 401)
GET http://localhost:3000/api/auth/me
